# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
 
on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install
    - run: npm run build-mode -- --mode production
    - run: |
        cp "CNAME" "./dist/CNAME"
    - run: |
        cp "404.html" "./dist/404.html"
    - run: |
        cp -r "files" "./dist/files"    
    - uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: site
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
